version: '3.8'

services:
  gelato-api:
    build: .
    container_name: gelato-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - gelato-network

  gelato-ui:
    image: gelato-ui
    container_name: gelato-ui
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - gelato-network

  postgres:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:${DB_PORT}"
    networks:
      - gelato-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - gelato-network

networks:
  gelato-network:
    driver: bridge
